use desktop_cli::packs::{parse_manifest, parse_stylesheet, project, ApplicationPack};
use desktop_cli::semantic::*;
use std::collections::{BTreeMap, BTreeSet};

fn element(id: u64, role: Role, name: &str, parent: Option<u64>) -> ElementSnapshot {
    ElementSnapshot { node:id, identity:ElementIdentity{native:NativeIdentity::Synthetic{key:format!("node-{id}")},stable_id:None}, role, native_role:NativeRole{backend:BackendKind::Mock,role:role.as_str().to_string(),subrole:None,numeric_id:None}, name:Some(name.to_string()), description:None, value:None, states:StateSet::default(), capabilities:BTreeSet::new(), actions:Vec::new(), geometry:None, parent, children:Vec::new(), relations:Vec::new(), properties:BTreeMap::new(), native:NativeMetadata::default() }
}

fn fixture_graph()->AccessibilityGraph{let mut graph=AccessibilityGraph::new(SessionId::new());let mut root=element(1,Role::Window,"Altium Designer",None);root.children=vec![2,3,4,5];graph.insert(root);let mut projects=element(2,Role::Tree,"Projects",Some(1));projects.children=vec![6];graph.insert(projects);graph.insert(element(6,Role::TreeItem,"Board1.PcbDoc",Some(2)));let mut properties=element(3,Role::Panel,"Properties",Some(1));properties.children=vec![7];graph.insert(properties);graph.insert(element(7,Role::TextInput,"Width",Some(3)));let mut save=element(4,Role::Button,"Save",Some(1));save.identity.stable_id=Some("SaveButton".into());save.capabilities.insert(CapabilityKind::Action);graph.insert(save);let mut dialog=element(5,Role::Dialog,"Confirm",Some(1));dialog.states.set_bool(State::Modal,true);dialog.children=vec![8];graph.insert(dialog);graph.insert(element(8,Role::Button,"OK",Some(5)));graph}

#[test]fn selectors_cover_semantics_structure_relations_and_geometry(){let mut graph=fixture_graph();assert_eq!(graph.query(&Selector::parse("@tree[name=\"Projects\"] > @treeitem").unwrap()),vec![6]);assert_eq!(graph.query(&Selector::parse("#SaveButton:supports(action)").unwrap()),vec![4]);graph.get_mut(7).unwrap().relations.push(Relation{kind:RelationKind::LabelledBy,targets:vec![6],native_name:Some("test".into())});assert_eq!(graph.query(&Selector::parse("@input:labelled-by(@treeitem[name=\"Board1.PcbDoc\"])").unwrap()),vec![7]);graph.get_mut(4).unwrap().geometry=Some(Geometry{bounds:Rect{x:100.0,y:100.0,width:50.0,height:25.0},coordinate_space:CoordinateSpace::ScreenLogical,visibility:Visibility::Visible,z_order:None});graph.get_mut(8).unwrap().geometry=Some(Geometry{bounds:Rect{x:100.0,y:140.0,width:50.0,height:25.0},coordinate_space:CoordinateSpace::ScreenLogical,visibility:Visibility::Visible,z_order:None});assert_eq!(graph.query(&Selector::parse("@button:below(#SaveButton)").unwrap()),vec![8]);}

#[test]fn pack_projection_preserves_critical_modal_content(){let mut graph=fixture_graph();let manifest=parse_manifest("schema=1\nid=\"fixture\"\nname=\"Fixture\"\n[view]\ndefault=\"workspace\"").unwrap();let stylesheet=parse_stylesheet(r#"@view workspace { default-projection: prune; @window { projection: flatten; } @tree[name="Projects"] { projection: keep; alias: projects; } @panel[name="Properties"] { projection: keep; alias: properties; } }"#).unwrap();let pack=ApplicationPack{manifest,stylesheet};let result=project(&mut graph,&pack,ObservationBudget::default()).unwrap();assert!(result.aliases.contains_key("projects"));assert!(result.aliases.contains_key("properties"));assert!(result.observation.roots.iter().any(|node|node.role==Role::Dialog));}

#[test]fn public_refs_become_stale_across_graph_generations(){let mut graph=fixture_graph();let reference=graph.element_ref_for(4);assert_eq!(graph.resolve_ref(&reference).unwrap(),4);graph.clear();assert!(graph.resolve_ref(&reference).is_err());}

#[test]fn observation_diff_tracks_appeared_disappeared_and_changed(){let mut graph=fixture_graph();let before=observe_raw(&graph,ObservationBudget::default());graph.get_mut(4).unwrap().name=Some("Save All".into());graph.remove(6);graph.insert(element(9,Role::Button,"Cancel",None));let after=observe_raw(&graph,ObservationBudget::default());let diff=before.diff(&after);assert!(!diff.changed.is_empty());assert!(!diff.appeared.is_empty());assert!(!diff.disappeared.is_empty());}
